#pragma once

#include <array>
#include <cstdint>
#include <string_view>

// Generated by tools/bsp/create_stellar_dev_wad.py --emit-cpp-header.
// Source of truth: tools/bsp/developer_textures.json.

namespace stellar::import::bsp::detail::generated {

inline constexpr std::uint32_t kDeveloperTextureSize = 128U;

enum class DeveloperTextureKind { kGrid, kPlayer, kWall };

struct DeveloperTextureSpec {
  std::string_view alias;
  std::string_view canonical_name;
  std::uint32_t spacing;
  DeveloperTextureKind kind;
};

inline constexpr std::array<DeveloperTextureSpec, 18> kDeveloperTextureSpecs{{
    DeveloperTextureSpec{"stellar_dev_grid_12", "stellar_dev_grid_12",
                         12U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev_grid_12", "stellar_dev_grid_12",
                         12U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev/grid_12", "stellar_dev_grid_12",
                         12U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"stellar_dev_grid_16", "stellar_dev_grid_16",
                         16U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev_grid_16", "stellar_dev_grid_16",
                         16U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev/grid_16", "stellar_dev_grid_16",
                         16U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"stellar_dev_grid_32", "stellar_dev_grid_32",
                         32U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev_grid_32", "stellar_dev_grid_32",
                         32U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev/grid_32", "stellar_dev_grid_32",
                         32U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"stellar_dev_grid_64", "stellar_dev_grid_64",
                         64U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev_grid_64", "stellar_dev_grid_64",
                         64U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"dev/grid_64", "stellar_dev_grid_64",
                         64U, DeveloperTextureKind::kGrid},
    DeveloperTextureSpec{"stellar_dev_player_72", "stellar_dev_player_72",
                         16U, DeveloperTextureKind::kPlayer},
    DeveloperTextureSpec{"dev_player_72", "stellar_dev_player_72",
                         16U, DeveloperTextureKind::kPlayer},
    DeveloperTextureSpec{"dev/player_72", "stellar_dev_player_72",
                         16U, DeveloperTextureKind::kPlayer},
    DeveloperTextureSpec{"stellar_dev_wall_96", "stellar_dev_wall_96",
                         16U, DeveloperTextureKind::kWall},
    DeveloperTextureSpec{"dev_wall_96", "stellar_dev_wall_96",
                         16U, DeveloperTextureKind::kWall},
    DeveloperTextureSpec{"dev/wall_96", "stellar_dev_wall_96",
                         16U, DeveloperTextureKind::kWall},
}};

} // namespace stellar::import::bsp::detail::generated
