#pragma once

#include <span>
#include <string>
#include <vector>

#include "stellar/scripting/ScriptValue.hpp"
#include "stellar/server/WorldSession.hpp"

namespace stellar::scripting {

/** @brief Result of applying one script-emitted native command. */
struct ScriptCommandResult {
    /** @brief Original script output event name. */
    std::string event_name;

    /** @brief True when native authoritative state accepted and applied the command. */
    bool applied = false;

    /** @brief Stable machine-readable result code. */
    std::string code;

    /** @brief Deterministic human-readable diagnostic for tools and tests. */
    std::string message;

    /** @brief Synchronous object-collider mutation exits generated by this command, if any. */
    std::vector<stellar::server::ObjectColliderEvent> object_collider_events;
};

/** @brief Summary of native application of script output events. */
struct ScriptCommandApplication {
    /** @brief Command results in the same order as input script output events. */
    std::vector<ScriptCommandResult> results;
};

/**
 * @brief Validate and apply supported script output events to an authoritative world session.
 *
 * Supported commands are intentionally narrow. Scripts emit primitive events only; this function
 * performs all validation and applies approved state changes through WorldSession APIs.
 */
[[nodiscard]] ScriptCommandApplication apply_script_commands(
    stellar::server::WorldSession& session,
    std::span<const ScriptOutputEvent> events) noexcept;

} // namespace stellar::scripting
